spring:
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        url: jdbc:mariadb://localhost:3306/toy
        username: root
        password: 123

mybatis:
  mapper-locations: mapper/**/*.xml


